export const JOBS = [
  { title: 'Frontend Developer', keywords: ['JavaScript', 'React', 'CSS', 'HTML', 'TypeScript', 'Redux', 'Sass', 'Responsive', 'UI', 'Web', 'Creative', 'Technical', 'Collaborative', 'Detail-oriented', 'Problem-solving'] },
  { title: 'Backend Developer', keywords: ['Python', 'Django', 'SQL', 'APIs', 'Flask', 'Node.js', 'Express', 'PostgreSQL', 'Server', 'Database', 'Technical', 'Analytical', 'Problem-solving', 'Efficient'] },
  { title: 'Machine Learning Engineer', keywords: ['Python', 'Machine Learning', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'Deep Learning', 'NLP', 'Research', 'Technical', 'Analytical', 'Innovative', 'Problem-solving'] },
  { title: 'Cloud Engineer', keywords: ['AWS', 'Azure', 'Cloud', 'DevOps', 'GCP', 'Docker', 'Kubernetes', 'Terraform', 'Automation', 'Technical', 'Reliable', 'Scalable', 'Security'] },
  { title: 'UI/UX Designer', keywords: ['Design', 'Figma', 'Sketch','Photoshop','Illustrator', 'UI', 'UX', 'Wireframes', 'Prototyping', 'Adobe XD', 'Creative', 'Empathy', 'User-centered', 'Visual', 'Collaborative', 'Communication'] },
  { title: 'Full Stack Developer', keywords: ['JavaScript', 'React', 'Node.js', 'SQL', 'APIs', 'MongoDB', 'Express', 'TypeScript', 'Versatile', 'Technical', 'Problem-solving', 'Teamwork'] },
  { title: 'Data Analyst', keywords: ['SQL', 'Python', 'Excel', 'Data Analysis', 'Power BI', 'Tableau', 'Visualization', 'Analytical', 'Detail-oriented', 'Reporting', 'Critical thinking'] },
  { title: 'Mobile Developer', keywords: ['React Native', 'Android', 'iOS', 'Swift', 'Kotlin', 'Flutter', 'Mobile Apps','Firebase', 'Technical', 'Creative', 'User-focused', 'Agile'] },
  { title: 'DevOps Engineer', keywords: ['CI/CD', 'Jenkins', 'Docker', 'Kubernetes', 'AWS', 'Terraform', 'Linux', 'Monitoring', 'Automation', 'Technical', 'Collaborative', 'Problem-solving'] },
  { title: 'Product Manager', keywords: ['Product Management', 'Roadmap', 'Agile', 'Scrum', 'Stakeholders', 'MVP', 'User Stories', 'Leadership', 'Strategic', 'Communication', 'Visionary', 'Organized'] },
  { title: 'QA Engineer', keywords: ['Testing', 'Automation', 'Selenium', 'Cypress', 'Manual Testing', 'Bug Tracking', 'Quality Assurance', 'Detail-oriented', 'Analytical', 'Problem-solving', 'Thorough'] },
  { title: 'Cybersecurity Analyst', keywords: ['Security', 'Penetration Testing', 'Firewalls', 'SIEM', 'Incident Response', 'Vulnerability Assessment', 'Encryption', 'Analytical', 'Technical', 'Attention to detail', 'Proactive'] },
  { title: 'Data Scientist', keywords: ['Python', 'R', 'Machine Learning', 'Data Mining', 'Pandas', 'Statistics', 'Big Data', 'Jupyter', 'Analytical', 'Research', 'Innovative', 'Problem-solving'] },
  { title: 'Frontend Architect', keywords: ['Architecture', 'React', 'TypeScript', 'Performance', 'Design Systems', 'Webpack', 'Micro Frontends', 'Technical', 'Leadership', 'Strategic', 'Innovative'] },
  { title: 'Content Writer', keywords: ['Writing', 'SEO', 'Content Creation', 'Blogging', 'Copywriting', 'Editing', 'WordPress', 'Creative', 'Communication', 'Storytelling', 'Detail-oriented'] },
  { title: 'Digital Marketer', keywords: ['Marketing', 'SEO', 'Google Ads', 'Social Media', 'Analytics', 'Email Marketing', 'Campaigns', 'Creative', 'Strategic', 'Communication', 'Analytical'] },
  { title: 'IT Support Specialist', keywords: ['Support', 'Troubleshooting', 'Windows', 'MacOS', 'Networking', 'Help Desk', 'Customer Service', 'Patient', 'Technical', 'Problem-solving', 'Communication'] },
  { title: 'Business Analyst', keywords: ['Business Analysis', 'Requirements', 'Process Improvement', 'Stakeholder Management', 'UML', 'Documentation', 'Workshops', 'Analytical', 'Communication', 'Organized', 'Detail-oriented'] },
]; 